// <auto-generated />
using System;
using MediaDock.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaDock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MediaDockDbContext))]
    partial class MediaDockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MediaDock.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LastErrorClass")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_class");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_message");

                    b.Property<Guid?>("LineageRootId")
                        .HasColumnType("TEXT")
                        .HasColumnName("lineage_root_id");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_job_id");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("preset_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_platform");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("SourcePlatform", "CompletedAt")
                        .HasDatabaseName("ix_jobs_source_platform_completed_at");

                    b.HasIndex("Status", "Priority", "ScheduledAt")
                        .HasDatabaseName("ix_jobs_status_priority_scheduled_at");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.JobArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("pk_job_artifacts");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_artifacts_job_id");

                    b.ToTable("job_artifacts", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.JobProgress", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<long?>("BytesDone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_done");

                    b.Property<long?>("BytesTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_total");

                    b.Property<int?>("EtaSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eta_seconds");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phase");

                    b.Property<double?>("SpeedBps")
                        .HasColumnType("REAL")
                        .HasColumnName("speed_bps");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId")
                        .HasName("pk_job_progress");

                    b.ToTable("job_progress", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.JobSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_json");

                    b.HasKey("Id")
                        .HasName("pk_job_specs");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_specs_job_id");

                    b.ToTable("job_specs", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Notifications.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_notifications_job_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Presets.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_presets");

                    b.ToTable("presets", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Schedules.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cron");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("JobTemplateJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("job_template_json");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_at");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Settings.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scope");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Key", "Scope")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.JobArtifact", b =>
                {
                    b.HasOne("MediaDock.Domain.Jobs.Job", "Job")
                        .WithMany("Artifacts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_artifacts_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.JobProgress", b =>
                {
                    b.HasOne("MediaDock.Domain.Jobs.Job", "Job")
                        .WithOne("Progress")
                        .HasForeignKey("MediaDock.Domain.Jobs.JobProgress", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_progress_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.JobSpec", b =>
                {
                    b.HasOne("MediaDock.Domain.Jobs.Job", "Job")
                        .WithOne("CurrentSpec")
                        .HasForeignKey("MediaDock.Domain.Jobs.JobSpec", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_specs_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MediaDock.Domain.Notifications.InAppNotification", b =>
                {
                    b.HasOne("MediaDock.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_jobs_job_id");
                });

            modelBuilder.Entity("MediaDock.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("CurrentSpec");

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
